[package]
name = "dada-collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
indexmap = "1.9.1"
typed-index-collections = "3.0.3"
smallvec = "1.11.0"
